---
title: "DA 3"
author: "Khawaja Hassan"
date: "1/23/2022"
output: pdf_document
---

```{r setup, include=FALSE}

rm(list=ls())

library(gridExtra)
#####################
## Import libraries##
#####################

library(tidyverse)
library(lspline)
library(cowplot)
library(boot)
library(estimatr)
library(huxtable)
library(stargazer)
library(modelsummary)
library(kableExtra)
library(dplyr)
library(data.table)
library(fixest)
library(caret)
library(skimr)
library(grid)
library(glmnet)
library(gridExtra)

```

```{r, include= F}
###########################################
## Set data dir, load theme and functions##
###########################################

dir <- "/Users/khawajahassan/BA21_Coding/Assignment_1/"

source(paste0(dir, "da_helper_function.R"))
source(paste0(dir, "theme_bg.R"))


# Importing the data
data_org <- fread("https://osf.io/4ay9x/download")



```

```{r,include=FALSE, warning=FALSE}

################
# Data Munging #
################

# Counting Number of Observation in each Occupation 
data_org[,.(Count=.N),by=occ2012]

# Filtering the data for the chosen occupation (Secondary-Teacher)
dt <- data_org %>% filter(occ2012==2320)
rm(data_org)
dt <-  data.table(dt)

# Creating a new wage per hour variable w
dt <- dt[, w := earnwke/uhours]

# Filtering on uhours to work on full time employee (minimum 40 hours)/181 employee dropped since they were working less than 40 hours 

dt <- dt[uhours >= 40]

# counting Number observation in each Education Level
# Filter:Bachelor's degree or Higher (dropping 11 observation )

dt[,.(count=.N), by= grade92]
dt <- dt[grade92 >= 43]

# Checking age greater than 20/ Min age is 22 with sufficient observation
dt[,.(count=.N), by= age]

# Looking at a quick summary of some of the key variables
datasummary(w + grade92 + age ~ Mean + SD + Min + Max + P25 + P75 + N , data = dt)

# Finding missing values

to_filter <- sapply(dt, function(x) sum(is.na(x)))
to_filter[to_filter > 0]

# dropping the ethnic column since there are 919 NA observation in the column 
dt <- dt[, ethnic := NULL]


```


```{r}
# Creating levels for grade92 variable in a new variable educ#
dt <- dt[grade92 == 43, educ := "Bachelors"]
dt <-dt[grade92 == 44, educ := "Masters"]
dt <-dt[grade92 == 45, educ := "Professional-School"]
dt <-dt[grade92 == 46, educ := "Doctorate degree"]

dt <- dt[, grade92 := NULL]

# Creating age squared column

dt <- dt[, agesq := age^2]

# checking result
datasummary(w*factor(educ) + age ~ Mean + SD + Min + Max + P25 + P75 + N , data = dt)

# Race

datasummary( w*factor(race) ~ N + SD +Percent() + Mean, data = dt )
# creating binary for white and non white
dt$white <- ifelse(dt$race==1,1,0)
dt <- dt %>%
  select(-c(race))

# Creating factor sex variable

dt <- dt[sex == 1, gender := "male"]
dt <- dt[sex == 2, gender := "female"]
dt <- dt %>%
  select(-c(sex))

# Creating factor variable for marital variable

dt[marital <= 2, married_status := "married"]
dt[marital <= 6 & marital >= 3, married_status := "separated"]
dt[marital == 7, married_status := "never married"]
dt <- dt %>%
  select(-c(marital))


# Ownchild

dt[,.(count=.N), by= ownchild]

# Create if individuals own child or no
  dt <- dt %>% mutate(ownchild=case_when(
  ownchild==0 ~ 0,
  TRUE ~ 1))
 datasummary( w*factor(ownchild) ~ N + SD + Mean, data = dt ) 
  
# dropping as it is the same as own child
dt <- dt %>%
  select(-chldpres)

# ind02( only elementary school)
datasummary( w*(ind02) ~ N + Percent() + Mean, data = dt ) 
# exclude from model
dt <- dt %>% select(-ind02)

# class
datasummary( w*factor(class) ~ N + Percent() + Mean, data = dt ) 
# include as factor
dt <- dt[class == "Government - Federal"| class=="Government - Local"|class=="Government - State", Sector := "Government"]
dt <- dt[class == "Private, For Profit"| class=="Private, Nonprofit", Sector := "Private"]

datasummary( w*factor(Sector) ~ N + Percent() + Mean, data = dt ) 
dt <- dt %>% select(-class)


# unionmme
datasummary( w*factor(unionmme) ~ N + Percent() + Mean, data = dt ) 

# state 
datasummary( w*factor(state) ~ N + Percent() + Mean, data = dt ) 

# lfsr94(mean difference is minor between these two so excluding from)
datasummary( w*factor(lfsr94) ~ N + Percent() + Mean, data = dt ) 
# exclude from model
dt <- dt %>% select(-lfsr94)

# prcitshp
datasummary( w*factor(prcitshp) ~ N + Percent() + Mean, data = dt ) 

dt <- dt[prcitshp=="Native, Born Abroad Of US Parent(s)"|prcitshp=="Native, Born in PR or US Outlying Area"|prcitshp=="Native, Born In US",origin := "Native"]
dt <- dt[prcitshp=="Foreign Born, Not a US Citizen"|prcitshp=="Foreign Born, US Cit By Naturalization",origin := "Foreign "]

dt <- dt %>% select(-prcitshp)

datasummary( w*factor(origin) ~ N + Percent() + Mean, data = dt ) 

##Creating region baased on states, Used Aftabs ideas to group these codes in region 

dt <- dt[stfips %in% c("WA", "OR", "MT", "ID", "WY", "NV", "UT", "CO", "AZ", "NM", "HI", "AK", "CA"), region := "west"]
dt <- dt[stfips %in% c("ND", "SD", "NE", "KS", "MN", "IA", "MO", "WI", "IL", "IN", "MI", "OH"), region := "mid-west"]
dt <- dt[stfips %in% c("OK", "TX", "AR", "LA", "KY", "TN", "MS", "AL", "WV", "VA", "NC", "SC", "GA", "FL", "DC","MD","DE"), region := "south"]
dt <- dt[stfips %in% c("PA", "NY", "VT", "NH", "ME","MA","RI","CT","NJ"), region := "north-east"]

# excluding unwanted variable
dt <- dt %>% select(-c(V1,hhid,intmonth,weight,occ2012,stfips,state))

```

```{r}
###############################
##Setting models interactions##
###############################

#1#
datasummary( w*factor(white)*gender ~ N + Percent() + Mean, data = dt ) 
# wage is  very different based on white and gender, so  interaction needed

#Boxplot#
white_gender <- ggplot(dt, aes(x = factor(white), y = w,
                              fill = factor(gender), color=factor(gender))) +
  geom_boxplot(alpha=0.8, na.rm=T, outlier.shape = NA, width = 0.8) +
  stat_boxplot(geom = "errorbar", width = 0.8, size = 0.3, na.rm=T)+
  scale_color_manual(name="",
                     values=c('red','blue')) +
  scale_fill_manual(name="",
                    values=c('red','blue')) +
  labs(x = "Race",y = "Wage per Hour (USD)")+
  scale_y_continuous(expand = c(0.01,0.01), limits=c(0, 70), breaks = seq(0,70, 10))+
  ggthemes::theme_economist() +
  theme(legend.position = c(0.15,0.85), axis.text.x = element_text(angle=45, vjust=.5))

#2#
datasummary( w*factor(educ)*gender ~ N + Percent() + Mean, data = dt )
# wage is very different based on education and gender

## Boxplot##
educ_gender <- ggplot(dt, aes(x = factor(educ), y = w,
                              fill = factor(gender), color=factor(gender))) +
  geom_boxplot(alpha=0.8, na.rm=T, outlier.shape = NA, width = 0.8) +
  stat_boxplot(geom = "errorbar", width = 0.8, size = 0.3, na.rm=T)+
  scale_color_manual(name="",
                     values=c('red','blue')) +
  scale_fill_manual(name="",
                    values=c('red','blue')) +
  labs(x = "Education",y = "Wage per Hour (USD)")+
  scale_y_continuous(expand = c(0.01,0.01), limits=c(0, 70), breaks = seq(0,70, 10))+
  ggthemes::theme_economist() +
  theme(legend.position = c(0.15,0.85), axis.text.x = element_text(angle=45, vjust=.5))


#3#
datasummary( w*married_status*gender ~ N + Percent() + Mean, data = dt )#3
# wage is very different based on , married_status and gender

## Boxplot##
Status_gender <- ggplot(dt, aes(x = factor(married_status), y = w,
                              fill = factor(gender), color=factor(gender))) +
  geom_boxplot(alpha=0.8, na.rm=T, outlier.shape = NA, width = 0.8) +
  stat_boxplot(geom = "errorbar", width = 0.8, size = 0.3, na.rm=T)+
  scale_color_manual(name="",
                     values=c('red','blue')) +
  scale_fill_manual(name="",
                    values=c('red','blue')) +
  labs(x = "Married status",y = "Wage per Hour (USD)")+
  scale_y_continuous(expand = c(0.01,0.01), limits=c(0, 70), breaks = seq(0,70, 10))+
  ggthemes::theme_economist() +
  theme(legend.position = c(0.15,0.85), axis.text.x = element_text(angle=45, vjust=.5))

#4#

datasummary( w*Sector*gender ~ N + Percent() + Mean, data = dt )#4
# wage is very different based on education and gender

## Boxplot##
Sector_gender <- ggplot(dt, aes(x = factor(Sector), y = w,
                              fill = factor(gender), color=factor(gender))) +
  geom_boxplot(alpha=0.8, na.rm=T, outlier.shape = NA, width = 0.8) +
  stat_boxplot(geom = "errorbar", width = 0.8, size = 0.3, na.rm=T)+
  scale_color_manual(name="",
                     values=c('red','blue')) +
  scale_fill_manual(name="",
                    values=c('red','blue')) +
  labs(x = "Sector",y = "Wage per Hour (USD)")+
  scale_y_continuous(expand = c(0.01,0.01), limits=c(0, 70), breaks = seq(0,70, 10))+
  ggthemes::theme_economist() +
  theme(legend.position = c(0.15,0.85), axis.text.x = element_text(angle=45, vjust=.5))


#5#
datasummary( w*unionmme*gender ~ N + Percent() + Mean, data = dt ) #4


## Boxplot##
Union_gender <- ggplot(dt, aes(x = factor(unionmme), y = w,
                              fill = factor(gender), color=factor(gender))) +
  geom_boxplot(alpha=0.8, na.rm=T, outlier.shape = NA, width = 0.8) +
  stat_boxplot(geom = "errorbar", width = 0.8, size = 0.3, na.rm=T)+
  scale_color_manual(name="",
                     values=c('red','blue')) +
  scale_fill_manual(name="",
                    values=c('red','blue')) +
  labs(x = "Union Membership",y = "Wage per Hour (USD)")+
  scale_y_continuous(expand = c(0.01,0.01), limits=c(0, 70), breaks = seq(0,70, 10))+
  ggthemes::theme_economist() +
  theme(legend.position = c(0.15,0.85), axis.text.x = element_text(angle=45, vjust=.5))

#6#
datasummary( w*unionmme*Sector ~ N + Percent() + Mean, data = dt )#3

## Boxplot##
Union_Sector <- ggplot(dt, aes(x = factor(unionmme), y = w,
                              fill = factor(Sector), color=factor(Sector))) +
  geom_boxplot(alpha=0.8, na.rm=T, outlier.shape = NA, width = 0.8) +
  stat_boxplot(geom = "errorbar", width = 0.8, size = 0.3, na.rm=T)+
  scale_color_manual(name="",
                     values=c('red','blue')) +
  scale_fill_manual(name="",
                    values=c('red','blue')) +
  labs(x = "Union Membership",y = "Wage per Hour (USD)")+
  scale_y_continuous(expand = c(0.01,0.01), limits=c(0, 70), breaks = seq(0,70, 10))+
  ggthemes::theme_economist() +
  theme(legend.position = c(0.15,0.85), axis.text.x = element_text(angle=45, vjust=.5))

#7#
datasummary( w*origin*Sector ~ N + Percent() + Mean, data = dt ) # not including since the wage differential is low
 #wage is not very different

#8#
datasummary(w*Sector*region ~ N + Percent() + Mean, data = dt)#4

## Boxplot##
Sector_Region<- ggplot(dt, aes(x = factor(region), y = w,
                              fill = factor(Sector), color=factor(Sector))) +
  geom_boxplot(alpha=0.8, na.rm=T, outlier.shape = NA, width = 0.8) +
  stat_boxplot(geom = "errorbar", width = 0.8, size = 0.3, na.rm=T)+
  scale_color_manual(name="",
                     values=c('red','blue')) +
  scale_fill_manual(name="",
                    values=c('red','blue')) +
  labs(x = "Region",y = "Wage per Hour (USD)")+
  scale_y_continuous(expand = c(0.01,0.01), limits=c(0, 70), breaks = seq(0,70, 10))+
  ggthemes::theme_economist() +
  theme(legend.position = c(0.15,0.85), axis.text.x = element_text(angle=45, vjust=.5))

#9#
datasummary(w*factor(white)*factor(married_status)  ~ N + Percent() + Mean, data = dt )#4

## Boxplot##
White_Status<- ggplot(dt, aes(x = factor(married_status), y = w,
                              fill = factor(white), color=factor(white))) +
  geom_boxplot(alpha=0.8, na.rm=T, outlier.shape = NA, width = 0.8) +
  stat_boxplot(geom = "errorbar", width = 0.8, size = 0.3, na.rm=T)+
  scale_color_manual(name="",
                     values=c('red','blue')) +
  scale_fill_manual(name="",
                    values=c('red','blue')) +
  labs(x = "Marriage Status",y = "Wage per Hour (USD)")+
  scale_y_continuous(expand = c(0.01,0.01), limits=c(0, 70), breaks = seq(0,70, 10))+
  ggthemes::theme_economist() +
  theme(legend.position = c(0.15,0.85), axis.text.x = element_text(angle=45, vjust=.5))


#10#(ask aftab)
datasummary(w*factor(educ)*region  ~ N + Percent() + Mean, data = dt )#4
#11#
datasummary(w*origin*factor(educ)  ~ N + Percent() + Mean, data = dt) 
# not including since the wage differential is minor and number of observation for Professional school is only 1
#12#
datasummary(w*factor(ownchild)*factor(gender) ~ N + Percent() + Mean, data = dt )
# not including since the wage differential is minor

```

```{r}
###################################
## Setting up Regressions models ##
###################################

model1 <- as.formula(w ~ educ)

model2 <- as.formula(w ~ educ+age+agesq)

model3 <- as.formula(w ~ educ+age+agesq+region+ownchild+w*factor(white)*gender+w*married_status*gender+w*unionmme*Sector+w*unionmme*gender)

model4 <- as.formula(w ~ educ+age+agesq+region+ownchild+w*factor(white)*gender+w*married_status*gender+w*unionmme*Sector+w*unionmme*gender+w*factor(educ)*region+w*factor(white)*factor(married_status)+w*Sector*region+w*unionmme*gender+w*Sector*gender)


### Running the regressions
reg1 <- feols(model1, data = dt , vcov="hetero")
reg2 <- feols(model2, data = dt , vcov="hetero")
reg3 <- feols(model3, data = dt , vcov="hetero")
reg4 <- feols(model4, data = dt , vcov="hetero")


 # evaluation of the models: using all the sample#
fitstat_register("k", function(x){length( x$coefficients ) - 1}, "No. Variables")           
etable( reg1 , reg2 , reg3 , reg4 , fitstat = c('aic','bic','rmse','r2','n','k'), keepFactors = TRUE )


#####################
# Cross-validation for better evaluation of predictive performance
# Simple k-fold cross validation setup:
# 1) Used method for estimating the model: "lm" - linear model (y_hat = b0+b1*x1+b2*x2 + ...)
# 2) set number of folds to use (must be less than the no. observations)
k <- 4

# We use the 'train' function which allows many type of model training -> use cross-validation
set.seed(200)
cv1 <- train(model1, dt, method = "lm", trControl = trainControl(method = "cv", number = k))

# Check the output:
cv1
summary(cv1)
cv1$results
cv1$resample

set.seed(200)
cv2 <- train(model2, dt, method = "lm", trControl = trainControl(method = "cv", number = k))
set.seed(200)
cv3 <- train(model3, dt, method = "lm", trControl = trainControl(method = "cv", number = k), na.action = "na.omit")
set.seed(200)
cv4 <- train(model4, dt, method = "lm", trControl = trainControl(method = "cv", number = k), na.action = "na.omit")

# Calculate RMSE for each fold and the average RMSE as well
cv <- c("cv1", "cv2", "cv3", "cv4")
rmse_cv <- c()

for(i in 1:length(cv)){
  rmse_cv[i] <- sqrt((get(cv[i])$resample[[1]][1]^2 +
                        get(cv[i])$resample[[1]][2]^2 +
                        get(cv[i])$resample[[1]][3]^2 +
                        get(cv[i])$resample[[1]][4]^2)/4)
}


# summarize results
cv_mat <- data.frame(rbind(cv1$resample[4], "Average"),
                     rbind(cv1$resample[1], rmse_cv[1]),
                     rbind(cv2$resample[1], rmse_cv[2]),
                     rbind(cv3$resample[1], rmse_cv[3]),
                     rbind(cv4$resample[1], rmse_cv[4])
)

colnames(cv_mat)<-c("Resample","Model1", "Model2", "Model3", "Model4")
cv_mat 

# Show model complexity and out-of-sample RMSE performance
m_comp <- c()
models <- c("reg1", "reg2", "reg3", "reg4")
for( i in 1 : length(cv) ){
  m_comp[ i ] <- length( get( models[i] )$coefficient  - 1 ) 
}

m_comp <- tibble( model = models , 
                  complexity = m_comp,
                  RMSE = rmse_cv )

ggplot( m_comp , aes( x = complexity , y = RMSE ) ) +
  geom_point(color='red',size=2) +
  geom_line(color='blue',size=0.5)+
  labs(x='Number of explanatory variables',y='Averaged RMSE on test samples',
       title='Prediction performance and model compexity') +
  ggthemes::theme_economist()

# plotting results
ggplot(dt, aes(x=predict(reg3, dt), y=w)) + 
  geom_point(alpha = 0.5) +
  geom_abline(intercept = 0, slope = 1, size = 0.5) +
  scale_x_continuous(limits = c(0,30)) + 
  scale_y_continuous(limits = c(0,60)) +
  ggthemes::theme_economist()
```

```{r}

## Arranging interaction plots into a grid for better presentation

grid.arrange(Sector_gender, Sector_Region, Status_gender, Union_gender,
             nrow = 2, ncol = 2)

grid.arrange( Union_Sector,white_gender,White_Status, nrow = 2, ncol = 2)


```

